config/routes.rb
Rails.application.routes.draw do
  mount TokenAuth::Engine => '/'
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  resource :version, only: :show

  namespace "api", constraints: { format: 'json' }  do
    get "lessons" => "lessons#index"
    get "study_identifier" => "study_identifiers#show"
  end

  scope "/(:locale)" do
    devise_for :users

    get "/participants/:participant_id/first_contacts/missed_appointment" => "first_contacts#missed_appointment", as: :missed_appointment

    resources :nurses, only: [] do
      resources :supervision_contacts, only: [:new, :create]
      resources :supervision_sessions, only: [:index, :new, :create]
      resources :supervisor_notes, only: [:new, :create, :edit, :update]
      resources :supervisor_notifications, only: [] do
        collection do
          put :clear
        end
      end
      resource :tasks_summary, only: :show
    end

    resources :participants, only: [:new, :create, :edit, :update] do
      resources :additional_contacts, only: [:new, :create]
      resource :call_to_schedule_final_appointment, only: [:new, :create, :edit, :update]
      resource :clinical_summary, only: :show
      resource :final_appointment, only: [:new, :create, :edit, :update]
      resource :first_contact, only: [:new, :create, :edit, :update]
      resource :first_appointment, only: [:new, :create, :edit, :update]
      resources :help_request_calls, only: [:new, :create]
      resources :lack_of_connectivity_calls, only: [:new, :create]
      resources :non_adherence_calls, only: [:new, :create]
      resources :patient_contacts, only: [:new, :create, :destroy]
      resource :second_contact, only: [:new, :create, :edit, :update]
      resource :smartphone, only: [:new, :create, :edit, :update]
      resources :tasks, only: :index do
        resources :scheduled_task_cancellations, only: [:new, :create]
        resources :scheduled_task_reschedulings, only: [:new, :create]
        member do
          put :resolve
          post :notify_supervisor
          delete :clear_latest_supervisor_notification
        end
      end
      resource :third_contact, only: [:new, :create, :edit, :update]
    end

    namespace "pending" do
      resources  :participants, only: :index
      get "activate/:id" => "participants#activate", as: :activate
      get "enroll/:id" => "participants#enroll", as: :enroll
    end
    
    namespace "active" do
      resources :participants, only: :show
      get "report/:id" => "participants#report", as: :report
    end

    resources :lessons do
      resources :slides
    end
    post "lessons/:id/slide_order" => "lessons#slide_order", as: :lesson_slide_order

    resource :nurse_supervisor_dashboard, only: :show
    resource :nurse_dashboard, only: :show

    get "/" => "dashboards#index", as: :dashboard

    root to: "dashboards#index"
  end

  # catch all for unrecognized routes
  get "(*unknown)", to: redirect("/")
  post "(*unknown)", to: redirect("/")
  match "(*unknown)", to: -> (hash) { [200, {}, [""]] }, via: :all
end

app/models/third_contact.rb
# frozen_string_literal: true
# Represents the third meeting of the Nurse with the Participant.
class ThirdContact < ActiveRecord::Base
  model_name.instance_variable_set :@route_key, "third_contact"

  FINAL_CALL_ABSOLUTE_DELAY = 6.weeks
  FINAL_CALL_RELATIVE_DELAY = 3.weeks

  belongs_to :participant
  has_many :patient_contacts

  accepts_nested_attributes_for :patient_contacts

  serialize :difficulties

  validates :participant,
            :contact_at,
            :session_length,
            :difficulties,
            presence: true

  after_initialize :populate_timestamps
  before_validation :sanitize_difficulties

  private

  def default_contact_at
    Tasks::FollowUpCallWeekThree.find_by(participant: participant)
                                .try(:scheduled_at) || Time.zone.now
  end

  def populate_timestamps
    self.contact_at ||= default_contact_at
  end

  def sanitize_difficulties
    return unless difficulties.try(:count).to_i >= 1

    self.difficulties = difficulties.delete_if(&:blank?)
    self.difficulties = nil if difficulties.empty?
  end
end

app/controllers/third_contacts_controller.rb
# frozen_string_literal: true
# Handles Third Contact info creation for active participant
class ThirdContactsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def self.filter_params(params)
    params.require(:third_contact).permit(
      :contact_at, :session_length,
      :notes,
      difficulties: [],
      patient_contacts_attributes: [:contact_reason, :note]
    )
  end

  def new
    @third_contact = find_participant.third_contact ||
                     find_participant.build_third_contact
  end

  def create
    @third_contact = find_participant.build_third_contact(third_contact_params)

    if @third_contact.save
      redirect_to participant_tasks_url(find_participant),
                  notice: [ThirdContact.model_name.human,
                           t("actioncontroller.saved"),
                           t("actioncontroller.successfully")].join(" ")
    else
      flash[:alert] = @third_contact.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @third_contact = find_participant.third_contact
  end

  def update
    @third_contact = find_participant.third_contact

    if @third_contact.update(third_contact_params)
      redirect_to active_participant_url(find_participant),
                  notice: [ThirdContact.model_name.human,
                           t("actioncontroller.saved"),
                           t("actioncontroller.successfully")].join(" ")
    else
      flash[:alert] = @third_contact.errors.full_messages.join(", ")
      render :edit
    end
  end

  private

  def third_contact_params
    self.class.filter_params params
  end

  def find_participant
    @participant ||= Participant.find(params[:participant_id])
  end

  def record_not_found
    redirect_to nurse_dashboard_url(current_user),
                alert: "Participant not found"
  end
end

app/views/third_contacts/_form.html.erb
<%= form_for @third_contact, url: participant_third_contact_path(@participant), method: @third_contact.valid? ? :patch : :post, html: {role: "form", class: "form-horizontal"} do |f| %>
  <div class="form-group">
    <%= f.label :contact_at, class: "col-md-4 control-label" %>
    <div class="col-md-7">
      <%= f.datetime_select :contact_at, { required: true }, { class: "date-select" } %>
      <br>
      <small><%= Time.zone %></small>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :session_length, class: "col-md-4 control-label" %>
    <div class="col-md-7">
      <%= f.number_field :session_length, min: 1, class: "form-control", required: true %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :difficulties, class: "col-md-4 control-label", required: true %>
    <%= hidden_field_tag "third_contact[difficulties][]", "" %>
    <div class="col-md-7">
      <p class="help-block"><%= t(".difficulties_help_block") %></p>
    </div>

    <div class="col-md-3 col-md-offset-4">
      <label class="checkbox">
        <%= t("conemo.views.shared.false").upcase %>
      </label>
      <label class="checkbox">
        <%= check_box_tag "third_contact[difficulties][]", t("conemo.views.shared.false").downcase, @third_contact.difficulties.try(:include?, t("conemo.views.shared.false").downcase) %> <%= t(".no_difficulties") %>
      </label>
    </div>

    <div class="col-md-3">
      <label class="checkbox">
        <%= t("conemo.views.shared.true").upcase %>
      </label>
      <% t("activerecord.field_options.third_contact.difficulties").each do |value| %>
        <label class="checkbox">
          <%= check_box_tag "third_contact[difficulties][]", value, @third_contact.difficulties.try(:include?, value) %> <%= value %>
        </label>
      <% end %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :notes, class: "col-md-4 control-label" %>
    <div class="col-md-7">
      <%= f.text_area :notes, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-4 col-md-7">
      <%= f.submit t("conemo.views.shared.save_button"), class: "btn btn-primary" %>
      <% referrer = params[:referrer] == "active_participant_path" ? active_participant_path(@participant) : participant_tasks_path(@participant) %>
      <%= link_to t("conemo.views.shared.cancel_button"), referrer, class: "btn btn-link" %>
    </div>
  </div>
<% end %>

app/views/third_contacts/edit.html.erb
<h1><%= ThirdContact.model_name.human %></h1>

<div class="row well">
  <div class="col-md-10">
    <%= render 'form', third_contact: @third_contact %>
  </div>
</div>

app/views/third_contacts/new.html.erb
<h1><%= ThirdContact.model_name.human %></h1>

<div class="row well">
  <div class="col-md-10">
    <%= render 'form' %>
  </div>
</div>