config/routes.rb
Rails.application.routes.draw do
  mount TokenAuth::Engine => '/'
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  resource :version, only: :show

  namespace "api", constraints: { format: 'json' }  do
    get "lessons" => "lessons#index"
    get "study_identifier" => "study_identifiers#show"
  end

  scope "/(:locale)" do
    devise_for :users

    get "/participants/:participant_id/first_contacts/missed_appointment" => "first_contacts#missed_appointment", as: :missed_appointment

    resources :nurses, only: [] do
      resources :supervision_contacts, only: [:new, :create]
      resources :supervision_sessions, only: [:index, :new, :create]
      resources :supervisor_notes, only: [:new, :create, :edit, :update]
      resources :supervisor_notifications, only: [] do
        collection do
          put :clear
        end
      end
      resource :tasks_summary, only: :show
    end

    resources :participants, only: [:new, :create, :edit, :update] do
      resources :additional_contacts, only: [:new, :create]
      resource :call_to_schedule_final_appointment, only: [:new, :create, :edit, :update]
      resource :clinical_summary, only: :show
      resource :final_appointment, only: [:new, :create, :edit, :update]
      resource :first_contact, only: [:new, :create, :edit, :update]
      resource :first_appointment, only: [:new, :create, :edit, :update]
      resources :help_request_calls, only: [:new, :create]
      resources :lack_of_connectivity_calls, only: [:new, :create]
      resources :non_adherence_calls, only: [:new, :create]
      resources :patient_contacts, only: [:new, :create, :destroy]
      resource :second_contact, only: [:new, :create, :edit, :update]
      resource :smartphone, only: [:new, :create, :edit, :update]
      resources :tasks, only: :index do
        resources :scheduled_task_cancellations, only: [:new, :create]
        resources :scheduled_task_reschedulings, only: [:new, :create]
        member do
          put :resolve
          post :notify_supervisor
          delete :clear_latest_supervisor_notification
        end
      end
      resource :third_contact, only: [:new, :create, :edit, :update]
    end

    namespace "pending" do
      resources  :participants, only: :index
      get "activate/:id" => "participants#activate", as: :activate
      get "enroll/:id" => "participants#enroll", as: :enroll
    end
    
    namespace "active" do
      resources :participants, only: :show
      get "report/:id" => "participants#report", as: :report
    end

    resources :lessons do
      resources :slides
    end
    post "lessons/:id/slide_order" => "lessons#slide_order", as: :lesson_slide_order

    resource :nurse_supervisor_dashboard, only: :show
    resource :nurse_dashboard, only: :show

    get "/" => "dashboards#index", as: :dashboard

    root to: "dashboards#index"
  end

  # catch all for unrecognized routes
  get "(*unknown)", to: redirect("/")
  post "(*unknown)", to: redirect("/")
  match "(*unknown)", to: -> (hash) { [200, {}, [""]] }, via: :all
end

app/models/participant.rb
# frozen_string_literal: true

# Study Participant
class Participant < ActiveRecord::Base
  include Status

  belongs_to :nurse, class_name: "User", foreign_key: :nurse_id
  has_one :call_to_schedule_final_appointment, dependent: :destroy
  has_one :final_appointment, dependent: :destroy
  has_one :first_appointment, dependent: :destroy
  has_one :first_contact, dependent: :destroy
  has_one :second_contact, dependent: :destroy
  has_one :smartphone, dependent: :destroy
  has_one :third_contact, dependent: :destroy
  has_many :additional_contacts, dependent: :destroy
  has_many :content_access_events, dependent: :destroy
  has_many :devices, dependent: :destroy
  has_many :help_messages, dependent: :destroy
  has_many :help_request_calls, dependent: :destroy
  has_many :lack_of_connectivity_calls, dependent: :destroy
  has_many :lessons, through: :content_access_events
  has_many :logins, dependent: :destroy
  has_many :non_adherence_calls, dependent: :destroy
  has_many :nurse_tasks, dependent: :destroy
  has_many :participant_start_dates, dependent: :destroy
  has_many :patient_contacts, dependent: :destroy
  has_many :planned_activities, dependent: :destroy
  has_many :session_events, dependent: :destroy

  UNASSIGNED ||= "unassigned"
  PENDING ||= "pending"
  ACTIVE ||= "active"
  DROPPED_OUT ||= "dropped_out"
  COMPLETED ||= "completed"
  STATUS ||= [UNASSIGNED, PENDING, ACTIVE, DROPPED_OUT, COMPLETED].freeze
  GENDER ||= %w( male female ).freeze
  TIMEZONES ||= {
    "en" => "Central Time (US & Canada)",
    "es-PE" => "Lima",
    "pt-BR" => "Brasilia"
  }.freeze

  validates :first_name,
            :last_name,
            :study_identifier,
            :family_health_unit_name,
            :address,
            :locale,
            presence: true

  validates :study_identifier, uniqueness: true
  validates :status, inclusion: { in: STATUS }
  validates :gender, inclusion: { in: GENDER }
  validates :contact_person_1_name,
            presence: true,
            if: proc { |participant|
                  participant.alternate_phone_1.present?
                }
  validates :contact_person_2_name,
            presence: true,
            if: proc { |participant|
                  participant.alternate_phone_2.present?
                }
  validates :study_identifier, :phone, :cell_phone, :alternate_phone_1,
            :alternate_phone_2, :emergency_contact_phone,
            :emergency_contact_cell_phone,
            format: /\A[0-9]+\z/, allow_nil: true, allow_blank: true

  before_validation :sanitize_number

  scope :dropped_out, -> { where(status: DROPPED_OUT) }
  scope :pending, -> { where(status: PENDING) }
  scope :unassigned, -> { where(status: UNASSIGNED) }
  scope :active, -> { where(status: ACTIVE) }
  scope :completed, -> { where(status: COMPLETED) }

  delegate :phone_identifier, to: :smartphone, allow_nil: true

  def active?
    status == ACTIVE
  end

  def start_date
    participant_start_dates.order(:created_at).first.try(:date)
  end

  def last_and_first_name
    "#{last_name}, #{first_name}"
  end

  def study_day(on: nil)
    result = nil

    if start_date
      Time.use_zone(TIMEZONES[locale]) do
        result = ((on || Time.zone.today) - start_date).to_i + 1
      end
    end

    result
  end

  def complete
    update status: COMPLETED
  end

  # helper for Rails Admin
  def status_enum
    [[ACTIVE], [DROPPED_OUT], [COMPLETED]]
  end

  private

  def sanitize_number
    return unless phone.respond_to?(:gsub)

    self.phone = phone.gsub(/[^0-9]/, "")
  end
end

app/controllers/active/participants_controller.rb
# frozen_string_literal: true
module Active
  # Managing Active Participants
  class ParticipantsController < ApplicationController
    helper do
      def token_for(participant)
        TokenAuth::ConfigurationToken
          .find_by(entity_id: participant.id)
          .try(:value)
      end
    end

    def show
      @participant = Participant.find(params[:id])
      authorize! :read, @participant
      @participant_contacts = ParticipantContactPresenter
                              .all_contacts_for(@participant)
    end

    def report
      @participant = Participant.find(params[:id])
      authorize! :read, @participant
      @lessons = Lesson.where(locale: I18n.locale).order(day_in_treatment: :asc)
      @participant_contacts = ParticipantContactPresenter
                              .scheduled_contacts_for(@participant)
    end
  end
end

app/controllers/participants_controller.rb
# frozen_string_literal: true
# Creating, Editing, Updating, and Deleting all participants.
class ParticipantsController < ApplicationController
  TASKS_PAGE = "tasks"

  def new
    @participant = Participant.new(locale: current_user.locale)
    authorize! :create, @participant
  end

  def create
    @participant = Participant.new(
      participant_params.merge(locale: current_user.locale)
    )
    authorize! :create, @participant

    if @participant.save
      redirect_to pending_participants_path,
                  notice: t("actioncontroller.participants.saved_participant") +
                          " " + t("actioncontroller.successfully")
    else
      flash[:alert] = @participant.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @participant = Participant.where(id: params[:id]).first
    authorize! :update, @participant
    referrer
  end

  def update
    @participant = Participant.where(id: params[:id]).first
    authorize! :update, @participant
    referrer

    if @participant.update(participant_params)
      after_update_path
    else
      flash[:alert] = @participant.errors.full_messages.join(", ")
      render :edit
    end
  end

  private

  def referrer
    @referrer ||= params[:referrer]
  end

  def participant_params
    params.require(:participant).permit(
      :first_name, :last_name, :study_identifier,
      :family_health_unit_name, :address, :phone, :cell_phone,
      :alternate_phone_1, :contact_person_1_name,
      :contact_person_1_relationship, :contact_person_1_other_relationship,
      :alternate_phone_2, :contact_person_2_name,
      :contact_person_2_relationship, :contact_person_2_other_relationship,
      :date_of_birth, :gender, :emergency_contact_name,
      :emergency_contact_relationship, :emergency_contact_other_relationship,
      :emergency_contact_address, :emergency_contact_phone,
      :emergency_contact_cell_phone, :status, :nurse_id
    )
  end

  def after_update_path
    flash[:notice] = t("actioncontroller.participants.saved_participant") +
                     " " + t("actioncontroller.successfully")

    if current_user.nurse? || referrer == TASKS_PAGE
      redirect_to participant_tasks_url(@participant)
    else
      redirect_to root_url(locale: current_user.locale)
    end
  end
end

app/controllers/pending/participants_controller.rb
# frozen_string_literal: true
module Pending
  # Managing pending participants.
  class ParticipantsController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    def index
      @unassigned_participants = Participant.unassigned.where(locale: params[:locale])
      authorize! :read, @unassigned_participants
    end

    def enroll
      @participant = Participant.find(params[:id])
      authorize! :update, @participant

      if @participant.update(status: Participant::PENDING)
        redirect_to pending_participants_path,
                    notice: "Successfully activated participant"
      else
        redirect_to pending_participants_path,
                    alert: @participant.errors.full_messages.join(", ")
      end
    end

    def activate
      @participant = Participant.find(params[:id])
      authorize! :read, @participant
      @nurses = User.where(role: "nurse", locale: params[:locale])
    end

    private

    def record_not_found
      redirect_to pending_participants_url, alert: "Participant not found"
    end
  end
end

app/views/active/participants/_additional_contact.html.erb
<% in_person = ['in person', 'en persona', 'presencial'].include?(additional_contact.kind.downcase) %>
<li class="<%= in_person ? 'timeline-inverted' : '' %>">
  <div class="timeline-badge <%= in_person ? '' : 'success' %>" style="<%= in_person ? 'background-color:orange' : '' %>">
    <% if in_person %>
      <i class="fa fa-user-md fa-lg"></i>
    <% else %>
      <i class="fa fa-phone-square"></i>
    <% end %>
  </div>

  <div class="timeline-panel">
    <div class="timeline-heading">
      <h4 class="timeline-title"><%= additional_contact.model_name.human.capitalize %></h4>

      <p><i class="fa fa-clock-o"></i> <%= t "activerecord.attributes.additional_contact.scheduled_at" %>: <%= l additional_contact.scheduled_at, format: :long %></p>
    </div>

    <div class="timeline-body">
      <p><strong><%= t "activerecord.attributes.additional_contact.kind" %>: </strong><%= additional_contact.kind %>      
    </div>
  </div>
</li>

app/views/active/participants/_call_to_schedule_final_appointment.html.erb
<li>
  <div class="timeline-badge success"><i class="fa fa-phone-square"></i></div>

  <div class="timeline-panel">
    <div class="timeline-heading">
      <h4 class="timeline-title">
        <% if can? :update, call_to_schedule_final_appointment %>
          <%= link_to(edit_participant_call_to_schedule_final_appointment_path(@participant, referrer: "active_participant_path"),
            class: "btn btn-primary") do %>
            <i class="fa fa-edit fa-lg"></i>
          <% end %>
        <% end %>
        <%= call_to_schedule_final_appointment.model_name.human %>
      </h4>

      <p><i class="fa fa-clock-o"></i> <%= call_to_schedule_final_appointment.class.human_attribute_name(:contact_at) %>: <%= l call_to_schedule_final_appointment.contact_at, format: :long %></p>
    </div>
  </div>
</li>

app/views/active/participants/_contact_info.html.erb
<h3><%= t ".heading" %> <%= link_to(edit_participant_path(participant, referrer: "tasks"), class: "btn btn-primary pull-right") do %><i class="fa fa-edit pull-right"></i><% end %></h3>

<p><strong><%= t "activerecord.attributes.participant.family_health_unit_name" %>:</strong>
  <%= participant.family_health_unit_name %></p>

<p><strong><%= t "activerecord.attributes.participant.phone" %>:</strong>
  <%= participant.phone %></p>

<p><strong><%= t "activerecord.attributes.participant.cell_phone" %>:</strong>
  <%= participant.cell_phone %></p>

<p><strong><%= t "activerecord.attributes.participant.address" %>:</strong>
  <%= participant.address %></p>

<p><strong><%= t "activerecord.attributes.participant.gender" %>: </strong>
  <%=t "conemo.views.participants.form.#{participant.gender}" %></p>

<p><strong><%= t "activerecord.attributes.participant.emergency_contact_phone" %>:</strong>
  <%= participant.emergency_contact_phone %></p>

<p><strong><%= t "activerecord.attributes.participant.emergency_contact_name" %>:</strong>
  <%= participant.emergency_contact_name %></p>

<p><strong><%= t "activerecord.attributes.participant.alternate_phone_1" %>:</strong>
  <%= participant.alternate_phone_1 %></p>

<p><strong><%= t "activerecord.attributes.participant.contact_person_1_name" %>:</strong>
  <%= participant.contact_person_1_name %></p>

<button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#contact-info" aria-expanded="false" aria-controls="contact-info">
  <%= t "tasks.index.see_all" %>
</button>

<div class="collapse" id="contact-info">
  <p><strong><%= t "activerecord.attributes.participant.date_of_birth" %>: </strong>
    <%= l participant.date_of_birth, format: :long %></p>

  <p><strong><%= t "activerecord.attributes.participant.emergency_contact_relationship" %>:</strong>
    <%= participant.emergency_contact_relationship %></p>

  <p><strong><%= t "activerecord.attributes.participant.emergency_contact_other_relationship" %>:</strong>
    <%= participant.emergency_contact_other_relationship %></p>

  <p><strong><%= t "activerecord.attributes.participant.emergency_contact_address" %>:</strong>
    <%= participant.emergency_contact_address %></p>

  <p><strong><%= t "activerecord.attributes.participant.emergency_contact_cell_phone" %>:</strong>
    <%= participant.emergency_contact_cell_phone %></p>

  <p><strong><%= t "activerecord.attributes.participant.contact_person_1_relationship" %>:</strong>
    <%= participant.contact_person_1_relationship %></p>

  <p><strong><%= t "activerecord.attributes.participant.contact_person_1_other_relationship" %>:</strong>
    <%= participant.contact_person_1_other_relationship %></p>

  <p><strong><%= t "activerecord.attributes.participant.alternate_phone_2" %>:</strong>
    <%= participant.alternate_phone_2 %></p>

  <p><strong><%= t "activerecord.attributes.participant.contact_person_2_name" %>:</strong>
    <%= participant.contact_person_2_name %></p>

  <p><strong><%= t "activerecord.attributes.participant.contact_person_2_relationship" %>:</strong>
    <%= participant.contact_person_2_relationship %></p>

  <p><strong><%= t "activerecord.attributes.participant.contact_person_2_other_relationship" %>:</strong>
    <%= participant.contact_person_2_other_relationship %></p>
</div>

app/views/active/participants/_final_appointment.html.erb
<li class="timeline-inverted">
  <div class="timeline-badge" style="background-color:orange"><i class="fa fa-user-md fa-lg"></i></div>

  <div class="timeline-panel">
    <div class="timeline-heading">
      <h4 class="timeline-title">
        <% if can? :update, final_appointment %>
          <%= link_to(edit_participant_final_appointment_path(final_appointment.participant, referrer: "active_participant_path"),
            class: "btn btn-primary") do %>
            <i class="fa fa-edit fa-lg"></i>
          <% end %>
        <% end %>
        <%= t "conemo.views.active.participants.show.final_appointment_heading" %>
      </h4>

      <p><i class="fa fa-clock-o"></i> <%= t "helpers.label.final_appointment.appointment_at" %>: <%= l final_appointment.appointment_at, format: :long %></p>
    </div>

    <div class="timeline-body">
      <p><strong><%= t "helpers.label.final_appointment.appointment_location" %>: </strong> <%= final_appointment.appointment_location %>

      <p><strong><%= t "helpers.label.final_appointment.phone_returned" %>:</strong> <%= t "conemo.views.shared.#{final_appointment.phone_returned}" %>
    </div>
  </div>
</li>

app/views/active/participants/_first_appointment.html.erb
<li class="timeline-inverted">
  <div class="timeline-badge" style="background-color:orange"><i class="fa fa-user-md fa-lg"></i></div>

  <div class="timeline-panel">
    <div class="timeline-heading">
      <h4 class="timeline-title">
        <% if can? :update, first_appointment %>
          <%= link_to(edit_participant_first_appointment_path(first_appointment.participant, referrer: "active_participant_path"), class: "btn btn-primary") do %>
            <i class="fa fa-edit fa-lg"></i>
          <% end %>
        <% end %>
        <%= first_appointment.model_name.human %></h4>

      <p><i class="fa fa-clock-o"></i> <%= t "helpers.label.first_appointment.appointment_at" %>: <%= l first_appointment.appointment_at, format: :long %></p>
    </div>

    <div class="timeline-body">
      <p><strong><%= t "helpers.label.first_appointment.appointment_location" %>: </strong> <%= first_appointment.appointment_location %>

      <p><strong><%= t "helpers.label.first_appointment.session_length" %>: </strong><%= first_appointment.session_length %>      
    </div>
  </div>
</li>

app/views/active/participants/_first_contact.html.erb
<li>
  <div class="timeline-badge success"><i class="fa fa-phone-square"></i></div>

  <div class="timeline-panel">
    <div class="timeline-heading">
      <h4 class="timeline-title">
        <% if can? :update, first_contact %>
          <%= link_to(edit_participant_first_contact_path(first_contact.participant, referrer: "active_participant_path"),
            class: "btn btn-primary") do %>
            <i class="fa fa-edit fa-lg"></i>
          <% end %>
        <% end %>
        <%= first_contact.model_name.human %></h4>

      <p><i class="fa fa-clock-o"></i> <%= t "helpers.label.first_contact.contact_at" %>: <%= l first_contact.contact_at, format: :long %></p>
    </div>
  </div>
</li>

app/views/active/participants/_help_request_call.html.erb
<li>
  <div class="timeline-badge success"><i class="fa fa-phone-square"></i></div>

  <div class="timeline-panel">
    <div class="timeline-heading">
      <h4 class="timeline-title"><%= help_request_call.model_name.human %></h4>

      <p><i class="fa fa-clock-o"></i> <%= t "activerecord.attributes.help_request_call.contact_at" %>: <%= l help_request_call.contact_at, format: :long %></p>
    </div>

    <div class="timeline-body">
      <p><strong><%= t "activerecord.attributes.help_request_call.explanation" %>: </strong><%= help_request_call.explanation %>      
    </div>
  </div>
</li>

app/views/active/participants/_lesson_legend.html.erb
<table class="table table-condensed">
  <tbody>
    <tr class="un-released">
      <td><%= t ".unreleased" %></td>
    </tr>
    <tr class="info">
      <td><%= t ".current" %></td>
    </tr>
    <tr class="slippage">
      <td><%= t ".completed_late" %></td>
    </tr>
    <tr class="warning">
      <td><%= t ".accessed_but_not_completed" %></td>
    </tr>
    <tr class="danger">
      <td><%= t ".not_accessed" %></td>
    </tr>
    <tr class="success">
      <td><%= t ".completed_on_time" %></td>
    </tr>
  </tbody>
</table>

app/views/active/participants/_lessons_table.html.erb
<% connectivity = DeviceConnectivityPresenter.new(participant) %>
<%= t ".last_seen" %> <%= connectivity.last_seen_at_str %>
<div class="tab-pane active" id="lessons">
  <table class="table table-bordered">
    <thead>
      <th></th>
      <th><%= t "conemo.views.active.participants.report.release_day" %></th>
      <th><%= t "conemo.views.active.participants.report.lesson" %></th>
      <th></th>
    </thead>
    <tbody>
      <% lessons.each_with_index do |lesson, index| %>
        <% release_date = participant.start_date ? (participant.start_date + lesson.day_in_treatment.days - 1.days) : nil %>
        <tr class="<%= participant.lesson_status(lesson) %>">
          <td class="release-day"><%= index + 1 %></td>
          <td class="release-date"><%= release_date ? l(release_date, format: :long) : "" %></td>
          <td>
            <%= lesson.title %>
          </td>
          <td style="text-align: center;">
            <% if !release_date.nil? &&
                  Time.zone.today >= release_date &&
                  connectivity.lack_of_on_release_day?(lesson.day_in_treatment - 1,
                                                       lessons.to_a[index + 1] ? lessons.to_a[index + 1].day_in_treatment - 1 : nil) %>
              <span class="fa-stack fa-lg" aria-hidden="true" title="No connectivity">
                <i class="fa fa-wifi fa-stack-1x"></i>
                <i class="fa fa-ban fa-stack-2x"></i>
              </span>
              <span class="sr-only">No connectivity</span>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/active/participants/_non_adherence_call.html.erb
<li>
  <div class="timeline-badge success"><i class="fa fa-phone-square"></i></div>

  <div class="timeline-panel">
    <div class="timeline-heading">
      <h4 class="timeline-title"><%= non_adherence_call.model_name.human %></h4>

      <p><i class="fa fa-clock-o"></i> <%= t "activerecord.attributes.non_adherence_call.contact_at" %>: <%= l non_adherence_call.contact_at, format: :long %></p>
    </div>

    <div class="timeline-body">
      <p><strong><%= t "activerecord.attributes.non_adherence_call.explanation" %>: </strong><%= non_adherence_call.explanation %>      
    </div>
  </div>
</li>

app/views/active/participants/_second_contact.html.erb
<li>
  <div class="timeline-badge success"><i class="fa fa-phone-square"></i></div>

  <div class="timeline-panel">
    <div class="timeline-heading">
      <h4 class="timeline-title">
        <% if can? :update, second_contact %>
          <%= link_to(edit_participant_second_contact_path(second_contact.participant, referrer: "active_participant_path"),
            class: "btn btn-primary") do %>
            <i class="fa fa-edit fa-lg"></i>
          <% end %>
        <% end %>
        <%= t "conemo.views.active.participants.show.second_contact_heading" %></h4>

      <p><i class="fa fa-clock-o"></i> <%= t "activerecord.attributes.second_contact.contact_at" %>: <%= l second_contact.contact_at, format: :long %></p>
    </div>

    <div class="timeline-body">
      <p><strong><%= t "activerecord.attributes.second_contact.difficulties" %>: </strong><%= second_contact.difficulties.join(", ") %>
    </div>

    <div class="timeline-body">
      <p><strong><%= t "activerecord.attributes.second_contact.session_length" %>: </strong><%= second_contact.session_length %>
    </div>
  </div>
</li>

app/views/active/participants/_third_contact.html.erb
<li>
  <div class="timeline-badge success"><i class="fa fa-phone-square"></i></div>

  <div class="timeline-panel">
    <div class="timeline-heading">
      <h4 class="timeline-title">
        <% if can? :update, third_contact %>
          <%= link_to(edit_participant_third_contact_path(third_contact.participant, referrer: "active_participant_path"),
            class: "btn btn-primary") do %>
            <i class="fa fa-edit fa-lg"></i>
          <% end %>
        <% end %>
        <%= t "conemo.views.active.participants.show.third_contact_heading" %></h4>

      <p><i class="fa fa-clock-o"></i> <%= t "activerecord.attributes.third_contact.contact_at" %>: <%= l third_contact.contact_at, format: :long %></p>
    </div>

    <div class="timeline-body">
      <p><strong><%= t "activerecord.attributes.third_contact.difficulties" %>: </strong><%= third_contact.difficulties.join(", ") %>
    </div>

    <div class="timeline-body">
      <p><strong><%= t "activerecord.attributes.third_contact.session_length" %>: </strong><%= third_contact.session_length %>
    </div>
  </div>
</li>

app/views/active/participants/report.html.erb
<h2><%= t(".clinical_summary") %></h2>

<div class="row report">
  <div class="col-md-7 col-sm-7 col-xs-7" id="main-report">
    <div class="tab-content">
      <%= render partial: "active/participants/lessons_table", :locals => {participant: @participant, lessons: @lessons} %>
    </div>
  </div>

  <div class="col-md-3 col-sm-3 col-xs-3">
    <%= render "active/participants/lesson_legend" %>

    <table class="table">
      <thead>
        <th class="text-center">
          <h3>
            <%= t 'conemo.views.active.participants.report.notes' %>
            <% if can? :create, PatientContact.new(participant: @participant) %>
              <%= link_to(new_participant_patient_contact_path(@participant), class: "btn btn-primary") do %>
                <span class="fa fa-edit fa-2x" aria-hidden="true"></span>
                <span class="sr-only">Write note</span>
              <% end %>
            <% end %>
          </h3>
        </th>
      </thead>
      <tbody>
        <% @participant_contacts.each do |contact| %>
          <tr>
            <td>
              <dl>
                <dt>
                  <%= contact.title %>
                  <% if contact.deletable? %>
                    <%= link_to "#{fa_icon 'times-circle'}".html_safe, participant_patient_contact_path(id: contact.id, participant_id: @participant.id), method: :delete, :"data-confirm" => "#{ t 'conemo.views.active.participants.report.delete' }", class: 'pull-right delete-note' %></dt>
                  <% end %>
                <dd><%= contact.note %></dd>
                <dd><em><%= l contact.timestamp, format: :long %></em></dd>
              </dl>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/active/participants/show.html.erb
<h2><%= t "active.participants.show.header" %></h2>

<% if @participant_contacts.present? %>
  <ul class="timeline">
    <% @participant_contacts.map(&:contact).each do |contact| %>
      <%= render partial: contact.class.to_s.underscore, object: contact %>
    <% end %>
  </ul>
<% end %>