config/routes.rb
Rails.application.routes.draw do
  mount TokenAuth::Engine => '/'
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  resource :version, only: :show

  namespace "api", constraints: { format: 'json' }  do
    get "lessons" => "lessons#index"
    get "study_identifier" => "study_identifiers#show"
  end

  scope "/(:locale)" do
    devise_for :users

    get "/participants/:participant_id/first_contacts/missed_appointment" => "first_contacts#missed_appointment", as: :missed_appointment

    resources :nurses, only: [] do
      resources :supervision_contacts, only: [:new, :create]
      resources :supervision_sessions, only: [:index, :new, :create]
      resources :supervisor_notes, only: [:new, :create, :edit, :update]
      resources :supervisor_notifications, only: [] do
        collection do
          put :clear
        end
      end
      resource :tasks_summary, only: :show
    end

    resources :participants, only: [:new, :create, :edit, :update] do
      resources :additional_contacts, only: [:new, :create]
      resource :call_to_schedule_final_appointment, only: [:new, :create, :edit, :update]
      resource :clinical_summary, only: :show
      resource :final_appointment, only: [:new, :create, :edit, :update]
      resource :first_contact, only: [:new, :create, :edit, :update]
      resource :first_appointment, only: [:new, :create, :edit, :update]
      resources :help_request_calls, only: [:new, :create]
      resources :lack_of_connectivity_calls, only: [:new, :create]
      resources :non_adherence_calls, only: [:new, :create]
      resources :patient_contacts, only: [:new, :create, :destroy]
      resource :second_contact, only: [:new, :create, :edit, :update]
      resource :smartphone, only: [:new, :create, :edit, :update]
      resources :tasks, only: :index do
        resources :scheduled_task_cancellations, only: [:new, :create]
        resources :scheduled_task_reschedulings, only: [:new, :create]
        member do
          put :resolve
          post :notify_supervisor
          delete :clear_latest_supervisor_notification
        end
      end
      resource :third_contact, only: [:new, :create, :edit, :update]
    end

    namespace "pending" do
      resources  :participants, only: :index
      get "activate/:id" => "participants#activate", as: :activate
      get "enroll/:id" => "participants#enroll", as: :enroll
    end
    
    namespace "active" do
      resources :participants, only: :show
      get "report/:id" => "participants#report", as: :report
    end

    resources :lessons do
      resources :slides
    end
    post "lessons/:id/slide_order" => "lessons#slide_order", as: :lesson_slide_order

    resource :nurse_supervisor_dashboard, only: :show
    resource :nurse_dashboard, only: :show

    get "/" => "dashboards#index", as: :dashboard

    root to: "dashboards#index"
  end

  # catch all for unrecognized routes
  get "(*unknown)", to: redirect("/")
  post "(*unknown)", to: redirect("/")
  match "(*unknown)", to: -> (hash) { [200, {}, [""]] }, via: :all
end

app/models/smartphone.rb
# frozen_string_literal: true
# Study phone given to Participant, or Participants own phone
class Smartphone < ActiveRecord::Base
  model_name.instance_variable_set :@route_key, "smartphone"
  belongs_to :participant

  validates :participant, :number, :phone_identifier, presence: true

  before_validation :sanitize_number

  private

  def sanitize_number
    return if number.nil?

    self.number = number.gsub(/[^0-9A-Z]/i, "")
  end
end

app/controllers/smartphones_controller.rb
# frozen_string_literal: true
# Handles smartphone info creation for active participant
class SmartphonesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  def new
    @smartphone = find_participant.smartphone ||
                  find_participant.build_smartphone
  end

  def create
    @smartphone = find_participant.build_smartphone(smartphone_params)

    if @smartphone.save
      successfully_saved
    else
      flash[:alert] = @smartphone.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @smartphone = find_participant.smartphone
  end

  def update
    @smartphone = find_participant.smartphone

    if @smartphone.update(smartphone_params)
      successfully_saved
    else
      flash[:alert] = @smartphone.errors.full_messages.join(", ")
      render :edit
    end
  end

  private

  def smartphone_params
    params.require(:smartphone).permit(:number, :phone_identifier)
  end

  def find_participant
    @participant ||= Participant.find(params[:participant_id])
  end

  def record_not_found
    redirect_to nurse_dashboard_url(current_user),
                alert: "Participant not found"
  end

  def successfully_saved
    redirect_to participant_tasks_url(find_participant),
                notice: [Smartphone.model_name.human,
                         t("actioncontroller.saved_m"),
                         t("actioncontroller.successfully")].join(" ")
  end
end

app/views/smartphones/_form.html.erb
<%= form_for @smartphone, url: participant_smartphone_path(@participant), method: @smartphone.valid? ? :patch : :post, html: {role: "form", class: "form-horizontal"} do |f| %>
    <div class="form-group">
      <%= f.label :number, class: "col-md-5 control-label" %>
      <div class="col-md-7">
        <%= f.telephone_field :number, class: "form-control", required: true %>
        <span id="helpBlock" class="help-block">ex. Lima: 95xxxxxxx; Sao Paulo: 11xxxxxxxxx </span>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :phone_identifier, class: "col-md-5 control-label" %>
      <div class="col-md-7">
        <%= f.text_field :phone_identifier, class: "form-control", required: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-5 col-md-7">
        <%= f.submit t("conemo.views.shared.save_button"), class: "btn btn-primary" %>
        <%= link_to t("conemo.views.shared.cancel_button"), participant_tasks_path(@participant), class: "btn btn-link" %>
      </div>
    </div>
<% end %>

app/views/smartphones/edit.html.erb
<h1><%= t "conemo.views.smartphones.new.heading" %></h1>

<div class="row well">
  <div class="col-md-10">
    <%= render 'form', smartphone: @smartphone %>
  </div>
</div>

app/views/smartphones/new.html.erb
<h1><%= t "conemo.views.smartphones.new.heading" %></h1>

<div class="row well">
  <div class="col-md-10">
    <%= render 'form', smartphone: @smartphone %>
  </div>
</div>