config/routes.rb
Rails.application.routes.draw do
  mount TokenAuth::Engine => '/'
  mount RailsAdmin::Engine => "/admin", as: "rails_admin"

  resource :version, only: :show

  namespace "api", constraints: { format: 'json' }  do
    get "lessons" => "lessons#index"
    get "study_identifier" => "study_identifiers#show"
  end

  scope "/(:locale)" do
    devise_for :users

    get "/participants/:participant_id/first_contacts/missed_appointment" => "first_contacts#missed_appointment", as: :missed_appointment

    resources :nurses, only: [] do
      resources :supervision_contacts, only: [:new, :create]
      resources :supervision_sessions, only: [:index, :new, :create]
      resources :supervisor_notes, only: [:new, :create, :edit, :update]
      resources :supervisor_notifications, only: [] do
        collection do
          put :clear
        end
      end
      resource :tasks_summary, only: :show
    end

    resources :participants, only: [:new, :create, :edit, :update] do
      resources :additional_contacts, only: [:new, :create]
      resource :call_to_schedule_final_appointment, only: [:new, :create, :edit, :update]
      resource :clinical_summary, only: :show
      resource :final_appointment, only: [:new, :create, :edit, :update]
      resource :first_contact, only: [:new, :create, :edit, :update]
      resource :first_appointment, only: [:new, :create, :edit, :update]
      resources :help_request_calls, only: [:new, :create]
      resources :lack_of_connectivity_calls, only: [:new, :create]
      resources :non_adherence_calls, only: [:new, :create]
      resources :patient_contacts, only: [:new, :create, :destroy]
      resource :second_contact, only: [:new, :create, :edit, :update]
      resource :smartphone, only: [:new, :create, :edit, :update]
      resources :tasks, only: :index do
        resources :scheduled_task_cancellations, only: [:new, :create]
        resources :scheduled_task_reschedulings, only: [:new, :create]
        member do
          put :resolve
          post :notify_supervisor
          delete :clear_latest_supervisor_notification
        end
      end
      resource :third_contact, only: [:new, :create, :edit, :update]
    end

    namespace "pending" do
      resources  :participants, only: :index
      get "activate/:id" => "participants#activate", as: :activate
      get "enroll/:id" => "participants#enroll", as: :enroll
    end
    
    namespace "active" do
      resources :participants, only: :show
      get "report/:id" => "participants#report", as: :report
    end

    resources :lessons do
      resources :slides
    end
    post "lessons/:id/slide_order" => "lessons#slide_order", as: :lesson_slide_order

    resource :nurse_supervisor_dashboard, only: :show
    resource :nurse_dashboard, only: :show

    get "/" => "dashboards#index", as: :dashboard

    root to: "dashboards#index"
  end

  # catch all for unrecognized routes
  get "(*unknown)", to: redirect("/")
  post "(*unknown)", to: redirect("/")
  match "(*unknown)", to: -> (hash) { [200, {}, [""]] }, via: :all
end

app/controllers/nurse_supervisor_dashboards_controller.rb
# frozen_string_literal: true
# Manage Nurse Supervisor display.
class NurseSupervisorDashboardsController < ApplicationController
  def show
    return redirect_to(root_url) unless current_user.respond_to?(:nurses)

    participants = Participant.where(nurse: current_user.nurses).includes(:nurse)
    @pending_participants = Participant.pending
                                       .where(locale: current_user.locale)
                                       .includes(:nurse)
    @active_participants = participants.active
    @completed_participants = participants.completed
    @dropped_out_participants = participants.dropped_out
    @dashboard = NurseSupervisorDashboardPresenter.new(current_user,
                                                       @active_participants)
    authorize! :update, @pending_participants
  end
end

app/views/nurse_supervisor_dashboards/_nurse.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h4>
      <%= link_to nurse.last_and_first_name, nurse_tasks_summary_path(nurse) %>
      <% if nurse.supervision_sessions.latest %>
        <small class="pull-right <%= SupervisionSessionPresenter.new(nurse.supervision_sessions.latest).css_class %>">
          <%= t ".last_supervision_session" %>: <%= l nurse.supervision_sessions.latest.session_at, format: :long %>
          <%= link_to t(".review"), nurse_supervision_sessions_path(nurse) %>
        </small>
      <% end %>
    </h4>

    <ul class="list-inline">
      <li><%= nurse.active_participants.count %> <%= Participant.model_name.human(count: nurse.active_participants.count) %></li>
      <li><%= nurse.current_tasks.count %> <%= NurseTask.model_name.human(count: nurse.current_tasks.count) %></li>
      <li><%= nurse.overdue_tasks.count %> <%= t ".overdue", count: nurse.overdue_tasks.count %></li>
      <li><%= nurse.family_health_unit_name %></li>
    </ul>
  </div>

  <div class="panel-body">
    <div class="btn-group" role="group" aria-label="Actions">
      <%= link_to t(".log_supervision_session"),
                  new_nurse_supervision_session_path(nurse),
                  { class: "btn btn-link" } %>

      <% if SupervisorNotification.active_for_nurse(nurse).exists? %>
        <span class="fa fa-exclamation-circle fa-2x" aria-hidden="true"></span>
        <span class="sr-only">Notification</span>
      <% end %>
    </div>

    <% if nurse.rescheduled_tasks.count + nurse.cancelled_tasks.count + nurse.cancelled_unscheduled_contacts.count > 0 %>
      <div class="row">
        <div class="col-md-12 col-sm-12">
          <button class="btn btn-info" type="button" data-toggle="collapse" data-target="#nurse-<%= nurse.id %>-tasks" aria-expanded="false" aria-controls="nurse-<%= nurse.id %>-tasks">
            <%= t ".toggle_tasks" %>
          </button>
        </div>
      </div>
    <% end %>

    <ul class="collapse list-unstyled" id="nurse-<%= nurse.id %>-tasks">
      <% (nurse.rescheduled_tasks + nurse.cancelled_tasks + nurse.cancelled_unscheduled_contacts).sort_by(&:updated_at).reverse.each do |task_change| %>
        <% if task_change.is_a? ScheduledTaskRescheduling %>
          <li class="text-info"><%= l task_change.updated_at, format: :long %> <%= Participant.model_name.human %> <%= task_change.participant_study_identifier %> <%= task_change.nurse_task %> <%= t ".rescheduled" %>: <%= task_change.explanation %></li>
        <% elsif task_change.cancelled? %>
          <% if [HelpRequestCall, LackOfConnectivityCall, NonAdherenceCall].include? task_change.class %>
            <li class="text-warning"><%= l task_change.updated_at, format: :long %> <%= Participant.model_name.human %> <%= task_change.participant.study_identifier %> <%= task_change.model_name.human %> <%= t ".cancelled" %>: <%= task_change.human_explanation %></li>
          <% else %>
            <li class="text-warning"><%= l task_change.updated_at, format: :long %> <%= Participant.model_name.human %> <%= task_change.participant.study_identifier %> <%= task_change %> <%= t ".cancelled" %>: <%= task_change.cancellation_explanation %></li>
          <% end %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/nurse_supervisor_dashboards/show.html.erb
<h3><%= Participant.model_name.human(count: 2) %></h3>

<div class="panel panel-default">
  <div class="panel-heading"><%= @pending_participants.count %> <%= t ".pending", count: @pending_participants.count %></div>

  <div class="panel-body">
    <table class="table table-bordered table-condensed table-hover filterable">
      <thead>
        <tr>
          <th><%= t "pending.participants.index.edit_info" %></th>
          <th><%= t "activerecord.attributes.participant.name" %></th>
          <th><%= t "activerecord.attributes.participant.study_identifier" %></th>
          <th><%= t "activerecord.attributes.participant.created_at" %></th>
          <th><%= t "pending.participants.index.activate" %></th>
        </tr>
      </thead>

      <tbody>
        <% @pending_participants.each do |participant| %>
          <tr>
            <td>
              <%= link_to(edit_participant_path(participant), class: "btn btn-link", :"aria-label" => t("pending.participants.index.edit_info")) do %>
                <span class="fa fa-edit fa-2x" aria-hidden="true"></span>
                <span class="sr-only"><%= t "pending.participants.index.edit_info" %></span>
              <% end %>
            </td>
            <td><%= participant.last_and_first_name %></td>
            <td><%= participant.study_identifier %></td>
            <td><%= l participant.created_at.to_date, format: :long %></td>
            <td>
              <%= link_to(pending_activate_path(participant), class: "btn btn-link", :"aria-label" => t("pending.participants.index.activate")) do %>
                <span class="fa fa-thumbs-up fa-2x" aria-hidden="true"></span>
                <span class="sr-only"><%= t "pending.participants.index.activate" %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><%= @active_participants.count %> <%= t ".active", count: @active_participants.count %></div>

  <div class="panel-body">
    <table class="table table-bordered table-condensed table-hover filterable">
      <thead>
        <tr>
          <th><%= t "pending.participants.index.edit_info" %></th>
          <th><%= Nurse.model_name.human %></th>
          <th></th>
          <th><%= t "activerecord.attributes.participant.name" %></th>
          <th><%= t "activerecord.attributes.participant.study_identifier" %></th>
          <th><%= t "activerecord.attributes.participant.created_at" %></th>
          <th><%= t "pending.participants.index.disqualify" %></th>
        </tr>
      </thead>

      <tbody>
        <% @active_participants.each do |participant| %>
          <tr>
            <td>
              <%= link_to(edit_participant_path(participant), class: "btn btn-link", :"aria-label" => t("pending.participants.index.edit_info")) do %>
                <span class="fa fa-edit fa-2x" aria-hidden="true"></span>
                <span class="sr-only"><%= t "pending.participants.index.edit_info" %></span>
              <% end %>
            </td>
            <td><%= participant.nurse.last_and_first_name %></td>
            <td>
              <%= link_to(pending_activate_path(participant), class: "btn btn-link", :"aria-label" => t("pending.participants.index.edit_info")) do %>
                <span class="fa fa-user-md fa-2x" aria-hidden="true"></span>
                <span class="sr-only"><%= t "pending.participants.index.edit_info" %></span>
              <% end %>
            </td>
            <td><%= participant.last_and_first_name %></td>
            <td><%= participant.study_identifier %></td>
            <td><%= l participant.created_at.to_date, format: :long %></td>
            <td>
              <%= link_to(participant_path(id: participant.id, participant: { status: Participant::DROPPED_OUT }),
                          method: :put,
                          class: "btn btn-link",
                          :"aria-label" => t("pending.participants.index.disqualify"),
                          :"data-confirm" => "#{ t 'pending.participants.index.disqualify_alert' }") do %>
                <span class="fa fa-thumbs-down fa-2x" aria-hidden="true"></span>
                <span class="sr-only"><%= t "pending.participants.index.disqualify" %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><%= @completed_participants.count %> <%= t ".completed", count: @completed_participants.count %></div>

  <div class="panel-body">
    <table class="table table-bordered table-hover filterable">
      <thead>
        <tr>
          <th><%= Nurse.model_name.human %></th>
          <th><%= t "activerecord.attributes.participant.name" %></th>
          <th><%= t "activerecord.attributes.participant.study_identifier" %></th>
          <th><%= t "activerecord.attributes.participant.created_at" %></th>
        </tr>
      </thead>

      <tbody>
        <% @completed_participants.each do |participant| %>
          <tr class="clickable-row" data-href="<%= active_participant_path(participant.id) %>">
            <td><%= participant.nurse.last_and_first_name %></td>
            <td><%= participant.last_and_first_name %></td>
            <td><%= participant.study_identifier %></td>
            <td><%= l participant.created_at.to_date, format: :long %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><%= @dropped_out_participants.count %> <%= t ".dropped_out", count: @dropped_out_participants.count %></div>

  <div class="panel-body">
    <table class="table table-bordered table-condensed table-hover filterable">
      <thead>
        <tr>
          <th><%= Nurse.model_name.human %></th>
          <th><%= t "activerecord.attributes.participant.name" %></th>
          <th><%= t "activerecord.attributes.participant.study_identifier" %></th>
          <th><%= t "activerecord.attributes.participant.created_at" %></th>
        </tr>
      </thead>

      <tbody>
        <% @dropped_out_participants.each do |participant| %>
          <tr class="clickable-row" data-href="<%= active_participant_path(participant.id) %>">
            <td><%= participant.nurse.last_and_first_name %></td>
            <td><%= participant.last_and_first_name %></td>
            <td><%= participant.study_identifier %></td>
            <td><%= l participant.created_at.to_date, format: :long %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<% if @dashboard.nurses.present? %>
  <h3><%= Nurse.model_name.human(count: @dashboard.nurses.count) %></h3>

  <%= render partial: "nurse", collection: @dashboard.overdue_nurses %>

  <%= render partial: "nurse", collection: @dashboard.current_nurses %>

  <%= render partial: "nurse", collection: @dashboard.complete_nurses %>
<% end %>